name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-gc
          cargo install wasm-bindgen-cli

      - name: Run tests
        run: cargo test --verbose

      - name: Build
        run: ./build.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
